export default {
  // ── App-wide ──
  appName: 'ClinicSathi',
  loading: 'Loading...',
  save: 'Save',
  cancel: 'Cancel',
  delete: 'Delete',
  edit: 'Edit',
  search: 'Search',
  noResults: 'No results found',
  confirm: 'Confirm',
  back: 'Back',
  yes: 'Yes',
  no: 'No',

  // ── Auth ──
  auth: {
    login: 'Login',
    logout: 'Logout',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    phone: 'Phone Number',
    clinicName: 'Clinic Name',
    clinicNamePlaceholder: 'e.g. Sunrise Health Clinic',
    loginTitle: 'Welcome Back',
    loginSubtitle: 'Sign in to manage your clinic',
    forgotPassword: 'Forgot Password?',
    loginButton: 'Sign In',
    signUpTitle: 'Create Account',
    signUpSubtitle: 'Register your clinic to get started',
    signUpButton: 'Sign Up',
    signUpFailed: 'Sign Up Failed',
    signUpSuccess: 'Account Created!',
    signUpSuccessMessage: 'Please check your email to verify your account, then sign in.',
    noAccount: "Don't have an account?",
    signUpLink: 'Sign Up',
    alreadyHaveAccount: 'Already have an account?',
    loginLink: 'Sign In',
    emailRequired: 'Email is required',
    emailInvalid: 'Invalid email address',
    passwordRequired: 'Password is required',
    passwordMin: 'Password must be at least 6 characters',
    confirmPasswordRequired: 'Please confirm your password',
    passwordMismatch: 'Passwords do not match',
    clinicNameRequired: 'Clinic name is required',
  },

  // ── Navigation tabs ──
  tabs: {
    dashboard: 'Dashboard',
    patients: 'Patients',
    appointments: 'Appointments',
    billing: 'Billing',
  },

  // ── Dashboard ──
  dashboard: {
    title: 'Dashboard',
    greetingMorning: 'Good Morning',
    greetingAfternoon: 'Good Afternoon',
    greetingEvening: 'Good Evening',
    totalPatients: 'Patients Today',
    upcomingAppointments: 'Upcoming',
    revenueToday: 'Revenue Today',
    todaySchedule: "Today's Schedule",
    emptySchedule: 'No appointments today',
    quickActions: 'Quick Actions',
    addPatient: 'Add Patient',
    newAppointment: 'New Appointment',
    newBill: 'New Bill',
  },

  // ── Patients ──
  patients: {
    title: 'Patients',
    addNew: 'Add New Patient',
    searchPlaceholder: 'Search by name or phone...',
    fullName: 'Full Name',
    phone: 'Phone Number',
    age: 'Age',
    gender: 'Gender',
    address: 'Address (District / City)',
    patientId: 'Patient ID',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    registerButton: 'Register Patient',
    noPatients: 'No patients registered yet',
    patientDetails: 'Patient Details',
    visitHistory: 'Visit History',
  },

  // ── Appointments ──
  appointments: {
    title: 'Appointments',
    newAppointment: 'New Appointment',
    selectPatient: 'Select Patient',
    selectDate: 'Select Date',
    selectTime: 'Select Time',
    assignDoctor: 'Assign Doctor',
    doctorName: 'Doctor Name',
    notes: 'Notes (optional)',
    bookButton: 'Book Appointment',
    status: 'Status',
    statusBooked: 'Booked',
    statusCompleted: 'Completed',
    statusCancelled: 'Cancelled',
    statusNoShow: 'No Show',
    markCompleted: 'Mark as Completed',
    markCancelled: 'Mark as Cancelled',
    markNoShow: 'Mark as No Show',
    noAppointments: 'No appointments found',
    todayTitle: "Today's Appointments",
  },

  // ── Billing ──
  billing: {
    title: 'Billing',
    newBill: 'New Bill',
    selectPatient: 'Select Patient',
    addService: 'Add Service',
    serviceName: 'Service Name',
    servicePrice: 'Price (NPR)',
    totalAmount: 'Total Amount',
    paymentStatus: 'Payment Status',
    paid: 'Paid',
    unpaid: 'Unpaid',
    markPaid: 'Mark as Paid',
    generateReceipt: 'Generate Receipt',
    shareReceipt: 'Share Receipt',
    noBills: 'No bills found',
    currency: 'NPR',
    createBillButton: 'Create Bill',
    downloadReport: 'Download Report',
    downloading: 'Preparing PDF...',
    reportSuccess: 'Report Generated!',
    reportError: 'Failed to generate report',
  },
};
