export default {
  // ── App-wide ──
  appName: 'क्लिनिकसाथी',
  loading: 'लोड हुँदैछ...',
  save: 'सेभ गर्नुस्',
  cancel: 'रद्द गर्नुस्',
  delete: 'मेट्नुस्',
  edit: 'सम्पादन गर्नुस्',
  search: 'खोज्नुस्',
  noResults: 'कुनै नतिजा भेटिएन',
  confirm: 'पुष्टि गर्नुस्',
  back: 'फर्कनुस्',
  yes: 'हो',
  no: 'होइन',

  // ── Auth ──
  auth: {
    login: 'लगिन',
    logout: 'लगआउट',
    email: 'इमेल',
    password: 'पासवर्ड',
    confirmPassword: 'पासवर्ड पुष्टि गर्नुस्',
    phone: 'फोन नम्बर',
    clinicName: 'क्लिनिकको नाम',
    clinicNamePlaceholder: 'जस्तै: सनराइज हेल्थ क्लिनिक',
    loginTitle: 'स्वागत छ',
    loginSubtitle: 'आफ्नो क्लिनिक व्यवस्थापन गर्न साइन इन गर्नुस्',
    forgotPassword: 'पासवर्ड बिर्सनुभयो?',
    loginButton: 'साइन इन',
    signUpTitle: 'खाता बनाउनुस्',
    signUpSubtitle: 'सुरु गर्न आफ्नो क्लिनिक दर्ता गर्नुस्',
    signUpButton: 'साइन अप',
    signUpFailed: 'साइन अप असफल',
    signUpSuccess: 'खाता सिर्जना भयो!',
    signUpSuccessMessage: 'कृपया आफ्नो इमेल प्रमाणित गर्नुस्, त्यसपछि साइन इन गर्नुस्।',
    noAccount: 'खाता छैन?',
    signUpLink: 'साइन अप',
    alreadyHaveAccount: 'पहिले नै खाता छ?',
    loginLink: 'साइन इन',
    emailRequired: 'इमेल आवश्यक छ',
    emailInvalid: 'अमान्य इमेल ठेगाना',
    passwordRequired: 'पासवर्ड आवश्यक छ',
    passwordMin: 'पासवर्ड कम्तिमा ६ अक्षरको हुनुपर्छ',
    confirmPasswordRequired: 'कृपया पासवर्ड पुष्टि गर्नुस्',
    passwordMismatch: 'पासवर्ड मिलेन',
    clinicNameRequired: 'क्लिनिकको नाम आवश्यक छ',
  },

  // ── Navigation tabs ──
  tabs: {
    dashboard: 'ड्यासबोर्ड',
    patients: 'बिरामी',
    appointments: 'अपोइन्टमेन्ट',
    billing: 'बिलिङ',
  },

  // ── Dashboard ──
  dashboard: {
    title: 'ड्यासबोर्ड',
    greetingMorning: 'शुभ प्रभात',
    greetingAfternoon: 'शुभ दिउँसो',
    greetingEvening: 'शुभ सन्ध्या',
    totalPatients: 'आजका बिरामी',
    upcomingAppointments: 'आउँदो',
    revenueToday: 'आजको आम्दानी',
    todaySchedule: 'आजको तालिका',
    emptySchedule: 'आज कुनै अपोइन्टमेन्ट छैन',
    quickActions: 'छिटो कार्य',
    addPatient: 'बिरामी थप्नुस्',
    newAppointment: 'नयाँ अपोइन्टमेन्ट',
    newBill: 'नयाँ बिल',
  },

  // ── Patients ──
  patients: {
    title: 'बिरामी',
    addNew: 'नयाँ बिरामी थप्नुस्',
    searchPlaceholder: 'नाम वा फोनले खोज्नुस्...',
    fullName: 'पूरा नाम',
    phone: 'फोन नम्बर',
    age: 'उमेर',
    gender: 'लिङ्ग',
    address: 'ठेगाना (जिल्ला / सहर)',
    patientId: 'बिरामी आईडी',
    male: 'पुरुष',
    female: 'महिला',
    other: 'अन्य',
    registerButton: 'बिरामी दर्ता गर्नुस्',
    noPatients: 'अहिलेसम्म कुनै बिरामी दर्ता भएको छैन',
    patientDetails: 'बिरामीको विवरण',
    visitHistory: 'भ्रमण इतिहास',
  },

  // ── Appointments ──
  appointments: {
    title: 'अपोइन्टमेन्ट',
    newAppointment: 'नयाँ अपोइन्टमेन्ट',
    selectPatient: 'बिरामी छान्नुस्',
    selectDate: 'मिति छान्नुस्',
    selectTime: 'समय छान्नुस्',
    assignDoctor: 'डाक्टर तोक्नुस्',
    doctorName: 'डाक्टरको नाम',
    notes: 'नोट (वैकल्पिक)',
    bookButton: 'अपोइन्टमेन्ट बुक गर्नुस्',
    status: 'स्थिति',
    statusBooked: 'बुक भएको',
    statusCompleted: 'सम्पन्न',
    statusCancelled: 'रद्द',
    statusNoShow: 'अनुपस्थित',
    markCompleted: 'सम्पन्न भनी चिन्ह लगाउनुस्',
    markCancelled: 'रद्द भनी चिन्ह लगाउनुस्',
    markNoShow: 'अनुपस्थित भनी चिन्ह लगाउनुस्',
    noAppointments: 'कुनै अपोइन्टमेन्ट भेटिएन',
    todayTitle: 'आजका अपोइन्टमेन्टहरू',
  },

  // ── Billing ──
  billing: {
    title: 'बिलिङ',
    newBill: 'नयाँ बिल',
    selectPatient: 'बिरामी छान्नुस्',
    addService: 'सेवा थप्नुस्',
    serviceName: 'सेवाको नाम',
    servicePrice: 'मूल्य (रु.)',
    totalAmount: 'कुल रकम',
    paymentStatus: 'भुक्तानी स्थिति',
    paid: 'भुक्तान भयो',
    unpaid: 'बाँकी छ',
    markPaid: 'भुक्तान भनी चिन्ह लगाउनुस्',
    generateReceipt: 'रसिद बनाउनुस्',
    shareReceipt: 'रसिद शेयर गर्नुस्',
    noBills: 'कुनै बिल भेटिएन',
    currency: 'रु.',
    createBillButton: 'बिल बनाउनुस्',
    downloadReport: 'रिपोर्ट डाउनलोड गर्नुहोस्',
    downloading: 'PDF तयार गर्दै...',
    reportSuccess: 'रिपोर्ट तयार भयो!',
    reportError: 'रिपोर्ट तयार गर्न विफल',
  },
};
